[package]
name = "app_base"
version = "0.1.0"
edition = "2021"

[dependencies]
event_manager = { path = "../event_manager" }
resource_manager = { path = "../resource_manager" }
logger = { path = "../logger" }